replicaCount: 1

image:
  repository: waas/runtime
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 55055

config:
  path: /app/configs/runtime
  files:
    log: ""
    transport: ""

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 500m
    memory: 128Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

probes:
  enabled: false