version: '3'

tasks:
  generate:
    desc: Generate all needed artifacts
    cmds:
      - echo "not implemented"

  build:
    desc: Build all application binary
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go build -ldflags="-s -w" -o ./bin/runtime ./cmd/runtime

  lint:
    desc: Run linter checks. Pass flags after '--' (e.g. task lint -- --fix)
    cmds:
      - golangci-lint run ./... {{.CLI_ARGS}}

  tests:
    desc: Run all tests
    cmds:
      - go test -v ./...

  images:
    desc: Build Docker images for the runtime application
    deps: [build]
    cmds:
      - docker build -f deployments/docker/runtime.dockerfile -t waas/runtime:latest .
      - docker build -f deployments/docker/runtime-debug.dockerfile -t waas/runtime-debug:latest .

  deploy:
    desc: Deploy runtime into local Kubernetes cluster
    deps: [images]
    cmds:
      - k3d image import waas/runtime:latest -c waas
      - >-
        helmfile
        --file deployments/helm/helmfile.yaml
        --environment local
        apply

  up:
    desc: Create local Kubernetes cluster
    cmds:
      - k3d cluster create --config deployments/k3d/local.yaml

  down:
    desc: Delete local Kubernetes cluster
    cmds:
      - k3d cluster delete --config deployments/k3d/local.yaml