config:
  files:
    log: |
      log:
        meta:
          service: runtime
          environment: local

        handlers:
          - name: runtime-info
            type: file
            level: info
            format: json

            file:
              location: ./log/runtime/

              rotation:
                enabled: true
                filename_pattern: runtime-info-YY-MM-DD-HH-mm-SS.log
                max_size: 1000000
                max_age: 30s
                max_backups: 5
                compress: true

    transport: |
      transport:
        grpc_server:
          listen_host: 0.0.0.0
          listen_port: 55055
      
          max_recv_msg_size: 8388608
          max_send_msg_size: 8388608
          max_header_list_size: 16384
      
          max_concurrent_streams: 1000
          initial_window_size: 1048576
          initial_conn_window_size: 1048576
      
          read_buffer_size: 32768
          write_buffer_size: 32768
      
          connection_timeout: 10s
      
          keepalive:
            enabled: true
            max_connection_idle: 5m
            max_connection_age: 30m
            max_connection_age_grace: 5m
            time: 2h
            timeout: 20s
      
            enforcement:
              min_time: 10s
              permit_without_stream: false
      
          tls:
            enabled: false
            cert_file: ""
            key_file: ""
            client_ca_file: ""
            require_client_cert: true
      
          reflection:
            enabled: true
      
          health_check:
            enabled: true