apiVersion: v1
kind: Service
metadata:
  name: runtime
  labels:
    {{- include "runtime.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "runtime.selectorLabels" . | nindent 4 }}

  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: grpc